adjective = input("Enter an adjective: ")
adjective_two = input("Enter another adjective: ")
bird = input('Enter a type of bird: ')
room = input('Enter a type of room in a house: ')
verb = input('Enter a verb in past tense: ')
verb_two = input('Enter a verb in present tense: ')
relative = input("Enter a relative/s name: ")
noun = input('Enter a noun: ')
liquid = input('Enter any kind of liquid: ')
verb_three = input('Enter a verb ending in ing: ')
bodypart = input('Enter any body part (plural): ')
noun_two = input('Enter a plural noun: ')
verb_four = input('Enter another verb ending in ing: ')
noun_three = input('Enter another noun: ')

print("It was a " + adjective + ", cold November Day.")
print("I woke up to the " + adjective_two + " smell of " + bird)
print("roasting in the " + room + " downstairs.")
print("I " + verb + " down the stairs to see if I could help " + verb_two + " the dinner.")
print("My mom said, 'See if '" + relative + "' needs a fresh " + noun + "So I carried a tray of glasses full of " + liquid + " into the " + verb_three + " room.")
print("When I got there, I couldn/'t believe my " + bodypart + "!")
print("There were " + noun_two + "" + verb_four + " on the " + noun_three + "!")